// Checks against fixtures generated by the Typescript library.
// See helpers/fixtures.ts in the repo root for the format.
use std::fs;

use fuqr::extras::encoders::{AlphanumericEncoder, MixedEncoder, NumericEncoder};
use fuqr::{generate_with_encoder, ByteEncoder, Encoder, FuqrError, GenerateOptions, QrCode};

fn parse_content(json: &str) -> String {
    let mut content = String::new();
    let mut chars = json.strip_prefix('"').unwrap().chars();
    loop {
        match chars.next().unwrap() {
            '"' => break,
            '\\' => content.push(match chars.next().unwrap() {
                'n' => '\n',
                't' => '\t',
                'r' => '\r',
                'b' => '\u{8}',
                'f' => '\u{c}',
                'u' => {
                    let hex: String = chars.by_ref().take(4).collect();
                    char::from_u32(u32::from_str_radix(&hex, 16).unwrap()).unwrap()
                }
                c => c,
            }),
            c => content.push(c),
        }
    }
    // "unit"*N means unit cycled to N chars
    match chars.as_str().strip_prefix('*') {
        Some(len) => content.chars().cycle().take(len.parse().unwrap()).collect(),
        None => {
            assert_eq!(chars.as_str(), "");
            content
        }
    }
}

fn fnv1a64(bytes: &[u8]) -> u64 {
    bytes.iter().fold(0xcbf29ce484222325, |hash, &byte| {
        (hash ^ byte as u64).wrapping_mul(0x100000001b3)
    })
}

fn run(mode: &str, content: &str, options: GenerateOptions) -> String {
    let mut scratch = vec![0; content.len()];
    let result = (|| -> Result<QrCode, FuqrError> {
        let encoder: &mut dyn Encoder = match mode {
            "numeric" => &mut NumericEncoder::new(content)?,
            "alphanumeric" => &mut AlphanumericEncoder::new(content)?,
            "byte" => &mut ByteEncoder::new(content),
            "mixed" => &mut MixedEncoder::new(content, &mut scratch),
            _ => panic!("bad mode {mode}"),
        };
        generate_with_encoder(encoder, options, &mut [])
    })();

    match result {
        Ok(qr) => {
            let width = qr.version as usize * 4 + 17;
            let hash = fnv1a64(&qr.matrix[..width * width]);
            format!("{}-{}-{}-{hash:016x}", qr.version, qr.ecl, qr.mask)
        }
        Err(err) => err.code().to_string(),
    }
}

#[test]
fn matches_fixtures() {
    let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/../helpers/fixtures");
    let mut errors = Vec::new();
    for entry in fs::read_dir(dir).unwrap() {
        let path = entry.unwrap().path();
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        let Some(mode) = name.strip_suffix(".txt") else {
            continue;
        };
        for (i, line) in fs::read_to_string(&path).unwrap().lines().enumerate() {
            let fields: Vec<&str> = line.splitn(7, ' ').collect();
            let [min_version, max_version, min_ecl, max_ecl, mask, expected, content] =
                fields[..].try_into().unwrap();
            let options = GenerateOptions {
                min_version: min_version.parse().unwrap(),
                max_version: max_version.parse().unwrap(),
                min_ecl: min_ecl.parse().unwrap(),
                max_ecl: max_ecl.parse().unwrap(),
                mask: mask.parse().unwrap(),
            };

            let actual = run(mode, &parse_content(content), options);
            if actual != expected {
                errors.push(format!(
                    "{name}:{}: expected {expected}, got {actual}",
                    i + 1
                ));
            }
        }
    }
    assert!(errors.is_empty(), "{:#?}", &errors[..errors.len().min(10)]);
}
