[package]
name = "furious-qr"
version = "2.1.0"
edition = "2021"
rust-version = "1.81"
license = "MIT"
authors = ["Kyle Zheng <kylezheng73@gmail.com>"]
description = "A small and hackable QR code generator"
repository = "https://github.com/zhengkyl/furious-qr/tree/main/rust"

[profile.release]
opt-level = "s"
lto = true

[features]
extras = []

[dev-dependencies]
furious-qr = { path = ".", features = ["extras"] }
serde_json = "1.0.151"
